export const AdEvents = {
  // TODO: Generate it using some script
  AD_REQUESTED: 'adRequested',
  AD_FIRST_PLAY: 'adFirstPlay',
  STARTED: 'started',
  PAUSED: 'paused',
  RESUMED: 'resumed',
  COMPLETED: 'completed',
  FIRST_QUARTILE: 'firstQuartile',
  MIDPOINT: 'midpoint',
  THIRD_QUARTILE: 'thirdQuartile',
  SKIPPED: 'skipped',
  SKIPPABLE_STATE_CHANGED: 'skippableStateChanged',
  CLICKED: 'adClickedEvent',
  TAPPED: 'tapped',
  ICON_FALLBACK_IMAGE_CLOSED: 'iconFallbackImageClosed',
  ICON_TAPPED: 'iconTapped',
  AD_BREAK_READY: 'adBreakReady',
  AD_PROGRESS: 'adProgress',
  AD_BREAK_STARTED: 'adBreakStarted',
  AD_BREAK_ENDED: 'adBreakEnded',
  AD_BREAK_FETCH_ERROR: 'adBreakFetchError',
  AD_BREAK_IGNORED: 'adBreakIgnored',
  CUEPOINTS_CHANGED: 'cuepointsChanged',
  PLAY_HEAD_CHANGED: 'playHeadChanged',
  LOADED: 'loaded',
  CONTENT_PAUSE_REQUESTED: 'contentPauseRequested',
  CONTENT_RESUME_REQUESTED: 'contentResumeRequested',
  ALL_ADS_COMPLETED: 'allAdsCompleted',
  AD_BUFFER_START: 'adBufferStart',
  AD_BUFFER_END: 'adBufferEnd',
  AD_PLAYBACK_INFO_UPDATED: 'adPlaybackInfoUpdated',
  ERROR: 'adError',
  DAI_SOURCE_SELECTED: 'daiSourceSelected',
  AD_WATERFALLING: 'adWaterFalling',
  AD_WATERFALLING_FAILED: 'adWaterFallingFailed'
};
